version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: screendiaries
      DATABASE_URL: mysql://root:@db:3306/screendiaries
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:@db:3306/screendiaries
    ports:
      - "8000:8000"
    command: ["sh", "-c", "/wait-for-it.sh db:3306 -- pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"]
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
