# Generated by Django 5.1.2 on 2024-10-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(fields=('content', 'user_profile'), name='unique_watchlist_item'),
        ),
    ]
