# Generated by Django 5.1.1 on 2024-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
