# Generated by Django 5.1.2 on 2024-10-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('activity_feed', 'user_profile'), name='unique_reaction'),
        ),
    ]
