# Generated by Django 5.1.2 on 2024-10-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_reaction_unique_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
