# Generated by Django 5.1.1 on 2024-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ratingcomment_timestamp_ratingreply_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='activity_feed_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
