# Generated by Django 5.1.2 on 2024-10-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_watchlistitem_unique_watchlist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('Follow', 'Follow'), ('Reply', 'Reply'), ('Reaction', 'Reaction')], max_length=8)),
                ('activity_feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.activityfeeditem')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originaluser', to='network.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='network.userprofile')),
            ],
        ),
    ]
