# Generated by Django 5.1.1 on 2024-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_content_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfeeditem',
            name='activity_type',
            field=models.CharField(choices=[('Review', 'Review'), ('Rating', 'Rating'), ('Comment', 'Comment'), ('Reply', 'Reply')], max_length=7),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series'), ('Episode', 'Episode')], max_length=7),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('Content Share', 'Content Share'), ('Activity Feed Share', 'Activity Feed Share'), ('Text', 'Text')], max_length=19),
        ),
        migrations.AlterField(
            model_name='ratingreaction',
            name='reaction',
            field=models.CharField(choices=[('Love', 'Love'), ('Thumbs Up', 'Thumbs Up'), ('Thumbs Down', 'Thumbs Down'), ('Laughing', 'Laughing'), ('Crying', 'Crying'), ('Surprised', 'Surprised'), ('Sick', 'Sick'), ('Angry', 'Angry')], max_length=11),
        ),
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.CharField(choices=[('Love', 'Love'), ('Thumbs Up', 'Thumbs Up'), ('Thumbs Down', 'Thumbs Down'), ('Laughing', 'Laughing'), ('Crying', 'Crying'), ('Surprised', 'Surprised'), ('Sick', 'Sick'), ('Angry', 'Angry')], max_length=11),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='status',
            field=models.CharField(choices=[('Currently Watching', 'Currently Watching'), ('Watched', 'Watched')], max_length=18),
        ),
    ]
