# Generated by Django 5.1.1 on 2024-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_activityfeeditem_activity_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('content', 'user_profile'), name='unique_rating'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('content', 'user_profile'), name='unique_review'),
        ),
    ]
