# Generated by Django 5.1.1 on 2024-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_message_activity_feed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='new user', max_length=200),
        ),
    ]
