# Generated by Django 5.1.2 on 2024-10-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='activity_feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.activityfeeditem'),
        ),
    ]
