# Generated by Django 5.1.2 on 2024-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_update_activity_feed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
