# Generated by Django 5.1.1 on 2024-10-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userprofile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
    ]
