# Generated by Django 5.1.2 on 2024-11-08 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_update_update_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='network.rating'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', True)), fields=('activity_feed', 'user_profile'), name='unique_reaction_activity_feed'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment', 'user_profile'), name='unique_reaction_comment'),
        ),
    ]
