# Generated by Django 5.1.2 on 2024-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_update_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
