# Generated by Django 5.1.2 on 2024-11-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_reaction_unique_reaction_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_activity_feed',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_comment',
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('activity_feed', 'comment', 'user_profile'), name='unique_reaction'),
        ),
    ]
