# Generated by Django 5.1.1 on 2024-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_userprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_cover',
            field=models.ImageField(blank=True, upload_to='network/images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_image.png', upload_to='network/images'),
        ),
    ]
