# Generated by Django 5.1.1 on 2024-10-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_userprofile_profile_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='network/images/default_profile_image.png', upload_to='network/images'),
        ),
    ]
