# Generated by Django 5.1.2 on 2024-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_reaction_unique_reaction_activity_feed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Reply', 'Reply'), ('Comment', 'Comment'), ('Reaction', 'Reaction'), ('CommentReaction', 'CommentReaction')], max_length=15),
        ),
    ]
