# Generated by Django 5.1.1 on 2024-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_cover',
            field=models.ImageField(blank=True, max_length=500, upload_to='network/images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='network/images/default_profile_img.png', max_length=500, upload_to='network/images'),
        ),
    ]
